kwak_portfolio_homepage:
    pattern:  /
    defaults: { _controller: kwakPortfolioBundle:Default:index }
kwak_portfolio_show:
    pattern:  /add
    defaults: { _controller: kwakPortfolioBundle:Default:add }

