kwak_portfolio_homepage:
    pattern:  /
    defaults: { _controller: kwakPortfolioBundle:Default:index }
kwak_portfolio_show:
    pattern:  /show/{id}
    defaults: { _controller: kwakPortfolioBundle:Default:show }

