parameters:
#    kwak_portfolio.example.class: kwak\PortfolioBundle\Example

services:
#    kwak_portfolio.example:
#        class: %kwak_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
